# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - uses: actions/checkout@v2
        
    - name: Test project
      run: ./gradlew test

    - name: Archive test report
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: tests/build/reports/tests/test
        retention-days: 10
      if: always()

  report:
    runs-on: ubuntu-latest
    needs: run-tests
    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: pages
    
      - name: Download test report
        uses: actions/download-artifact@v3
        with:
          name: test-report
          path: test-report
      
      - name: Push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add test-report
          git commit -m "[AUTO] Generated test-report"
          git push
